rvm: 2.2
sudo: required
services: docker

addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk

env:
  matrix:
  - INSTANCE=installer-mysql-centos-6
  - INSTANCE=installer-mysql-ubuntu-1204
  - INSTANCE=installer-postgresql-ubuntu-1204
  - INSTANCE=standalone-mysql-ubuntu-1404
  - INSTANCE=standalone-postgresql-centos-6
  - INSTANCE=standalone-postgresql-ubuntu-1404

# Don't `bundle install`
install: echo "skip bundle install"

# Ensure we make ChefDK's Ruby the default
before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-docker
  - /opt/chefdk/embedded/bin/chef gem install rubocop -v 0.37
script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/rubocop --version
  - /opt/chefdk/embedded/bin/rubocop
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic . --exclude spec
  - /opt/chefdk/embedded/bin/rspec
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
