# Use container-based infrastructure in Travis
sudo: false

language: ruby
bundler_args: --without integration
rvm:
  - 2.2.0
before_script:
  - bundle exec berks install
script:
  - bundle exec rake travis
